import type { Metadata } from 'next';
import {Advent_Pro} from 'next/font/google'
import '@/style/global.scss'

const yanoneKaffeesatz = Advent_Pro({
    weight: ['500', '600'],
    subsets: ['cyrillic'],
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${yanoneKaffeesatz.className}`}>{children}</body>
        </html>
    );
}
